name: Evergreen

on:
  schedule:
    # Every 5PM on Sunday PT
    - cron: "0 17 * * 0"

  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: latest

      - run: npm i -g pnpm yarn bun @antfu/ni
      - run: nlx taze latest -wif

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@main
        with:
          title: Bump dependencies
